CREATE TABLE IF NOT EXISTS "UserType" (
    id SERIAL PRIMARY KEY,
    type VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS "User" (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    userType INT,
    FOREIGN KEY (userType) REFERENCES "UserType" (id)
);